spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.131:3306/tiendavirtual?serverTimezone=UTC
    username: root
    password: 2022A!tia   
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.131:8761/eureka
server:
  port: 6000 
