spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.131:3306/cursos?serverTimezone=UTC
    username: root
    password: 2022A!tia   
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.131:8761/eureka
  instance:
    # instance-id: instancia0
    # instance-id: instancia1
    instance-id: instancia2
server:
  # port: 5000 
  # port: 5001
  port: 5002
  
